<center><h3>SEIRD</h3></center>

$$\frac{\partial S_n}{\partial t}=-\beta\sigma_nS_n\left(\sum_m{k_{n,m}I_m}\right)$$
$$\frac{\partial E_n}{\partial t}=\beta\sigma_nS_n\left(\sum_m{k_{n,m}I_m}\right)-\varepsilon E_n$$
$$\frac{\partial I_{s,n}}{\partial t}=\varepsilon f_s E_n - \left(\gamma_s + \delta_n\right)I_{s,n}$$
$$\frac{\partial I_{a,n}}{\partial t}=\varepsilon \left(1-f_s\right)E_n-\gamma_aI_{a,n}$$
$$\frac{\partial R_{n}}{\partial t}=\gamma_aI_{a,n}+\gamma_sI_{s,n}$$
$$\frac{\partial D_{n}}{\partial t}=\delta_nI_{s,n}$$

In [14]:
from utils.example_coefficient_matrices import sweden_coefficients
from utils.example_contact_matrices import sweden_contact_matrix
from utils.mathematics import solve_SEIRD
import matplotlib.pyplot as plt
import numpy as np

In [49]:
def cutout(array, index):
    return np.delete(array, index, axis=0)

In [20]:
t_range = (0, 100)
y0 = np.matrix([
    [0.125, 0, 1e-4, 0, 0, 0],
    [0.125, 0, 1e-4, 1e-4, 0, 0],
    [0.125, 0, 1e-4, 0, 0, 0],
    [0.125, 0, 1e-4, 0, 0, 0],
    [0.125, 0, 1e-4, 0, 0, 0],
    [0.125, 0, 1e-4, 0, 0, 0],
    [0.125, 0, 1e-4, 0, 0, 0],
    [0.125, 0, 1e-4, 0, 0, 0],
]).T
y0 = np.matrix([
    [0.125, 0.125,0.125,0.125,0.125,0.125,0.125,0.125],
    [0.000, 0.000,0.000,0.000,0.000,0.000,0.000,0.000],
    [1e-4, 1e-4,1e-4,1e-4,1e-4,1e-4,1e-4,1e-4],
    [0,1e-4,0,0,0,0.000,0.000,0.000],
    [0.000, 0.000,0.000,0.000,0.000,0.000,0.000,0.000],
    [0.000, 0.000,0.000,0.000,0.000,0.000,0.000,0.000]])
print(y0)
t_values = np.linspace(0, 100, 10000)
y_values = []
for n in range(0, 8):
    beta_n = sweden_coefficients[0, n]
    sigma_n = sweden_coefficients[1, n]
    epsilon_n = sweden_coefficients[2, n]
    f_sn = sweden_coefficients[3, n]
    gamma_sn = sweden_coefficients[4, n]
    gamma_an = sweden_coefficients[5, n]
    delta_n = sweden_coefficients[6, n]
    (beta_i, sigma_i, epsilon_i, f_si, gamma_si, gamma_ai, delta_i) = (sweden_coefficients[i, n] for i in range(7))
    print(beta_i)
    assert beta_n == beta_i
    assert sigma_n == sigma_i
    assert epsilon_n == epsilon_i
    assert f_sn == f_si
    assert gamma_sn == gamma_si
    assert gamma_an == gamma_ai
    assert delta_n == delta_i
    # check if this is correct
    # have to cut out the current age group element
    
    sum_m_contact_nm_times_I_m = sweden_contact_matrix[n, :].dot(y0[:, 2]+y0[:, 3])[0, 0]
    y_values.append(solve_SEIRD(
        t_range,
        np.asarray(y0[n, :]).reshape(-1),
        beta_n,
        sigma_n,
        epsilon_n,
        f_sn,
        gamma_sn,
        gamma_an,
        delta_n,
        sum_m_contact_nm_times_I_m,
        t_values
    ))

    
    print(beta_n, sigma_n, epsilon_n, f_sn, gamma_sn, gamma_an, delta_n, sweden_contact_matrix[n, :], y0[:, 2]+y0[:, 3], sum_m_contact_nm_times_I_m)
    print()
print(y0[1:,2]+y0[1:,3], sweden_contact_matrix[1, 1:], sweden_contact_matrix[1, 1:].dot(y0[1:, 2]+y0[1:, 3])[0, 0])
# plot solution
fig, (ax1, ax2, ax3, ax4, ax5, ax6) = plt.subplots(6, 1, sharex=True)
ax1.plot(t_values, y_values[0].y[3, :])
ax2.plot(t_values, y_values[1].y[3, :])
ax3.plot(t_values, y_values[2].y[3, :])
ax4.plot(t_values, y_values[3].y[3, :])
ax5.plot(t_values, y_values[4].y[3, :])
ax6.plot(t_values, y_values[5].y[3, :])

    
# plt.plot(t_values, y_values[0].y[0, :], label="S")
# plt.plot(t_values, y_values[0].y[1, :], label="E")
# plt.plot(t_values, y_values[0].y[2, :], label="I_s")
# plt.plot(t_values, y_values[0].y[3, :], label="I_a")
# plt.plot(t_values, y_values[0].y[4, :], label="R")
# plt.plot(t_values, y_values[0].y[5, :], label="D")
plt.legend()
plt.subplots_adjust(left=0, right=3, top=3, bottom=0)
plt.show()


[[1.25e-01 1.25e-01 1.25e-01 1.25e-01 1.25e-01 1.25e-01 1.25e-01 1.25e-01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [1.00e-04 1.00e-04 1.00e-04 1.00e-04 1.00e-04 1.00e-04 1.00e-04 1.00e-04]
 [0.00e+00 1.00e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]]
2.5e-05


ValueError: shapes (1,8) and (6,1) not aligned: 8 (dim 1) != 6 (dim 0)